# Generated by Django 4.1.3 on 2023-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('CNTS', 'Choose Not To Say')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba')], max_length=2, null=True),
        ),
    ]
