# Generated by Django 4.1.3 on 2022-11-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('niche', models.CharField(blank=True, max_length=200, null=True)),
                ('company_size', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_followers', models.IntegerField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_followers', models.IntegerField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_followers', models.IntegerField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_followers', models.IntegerField(blank=True, null=True)),
                ('tik_tok_url', models.URLField(blank=True, null=True)),
                ('tit_tok_followers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('tik_tok_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('niche', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_followers', models.IntegerField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_followers', models.IntegerField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_followers', models.IntegerField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_followers', models.IntegerField(blank=True, null=True)),
                ('tik_tok_url', models.URLField(blank=True, null=True)),
                ('tit_tok_followers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_client',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_freecancer',
            new_name='is_brand',
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
