# Generated by Django 4.1.5 on 2023-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_brand_budget_brand_contact_person_brand_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba'), ('Pg', 'Pidgin'), ('Ur', 'Urhobo')], max_length=2, null=True, verbose_name='Please select your languages'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='niche',
            field=models.CharField(blank=True, choices=[('Sc', 'Science'), ('Sp', 'Sport'), ('Et', 'Entertainment'), ('Tc', 'Tech'), ('Ht', 'Health'), ('Bs', 'Business'), ('Ot', 'Others')], max_length=200, null=True, verbose_name='Please select your niche'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba'), ('Pg', 'Pidgin'), ('Ur', 'Urhobo')], max_length=2, null=True, verbose_name='Please select your languages'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='niche',
            field=models.CharField(blank=True, choices=[('Sc', 'Science'), ('Sp', 'Sport'), ('Et', 'Entertainment'), ('Tc', 'Tech'), ('Ht', 'Health'), ('Bs', 'Business'), ('Ot', 'Others')], max_length=200, null=True, verbose_name='Please select your niche'),
        ),
    ]
