# Generated by Django 4.1.3 on 2022-12-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_brand_employee_influencer_remove_freelancer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='niche',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
