# Generated by Django 4.1.3 on 2023-01-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_brand_budget_brand_contact_person_brand_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='language',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='language',
        ),
    ]
