# Generated by Django 4.1.3 on 2022-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_influencer_niche'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='youtube_subscriber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_subscriber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user-default.png', null=True, upload_to='static/profile/images'),
        ),
    ]
