# Generated by Django 4.1.3 on 2023-01-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_brand_language_remove_influencer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba')], max_length=2, null=True),
        ),
    ]
