# Generated by Django 4.1.3 on 2023-01-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_brand_youtube_subscriber_brand_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
