# Generated by Django 4.1.3 on 2023-01-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_brand_language_influencer_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='language',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='language',
        ),
    ]
