# Generated by Django 4.1.3 on 2023-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_brand_language_influencer_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Portuguese'), ('sp', 'Spanish'), ('Hi', 'Hindi'), ('Ru', 'Russian'), ('Ja', 'Japanese'), ('Ar', 'Arabic'), ('Fr', 'French'), ('It', 'Italian'), ('Tu', 'Turkish'), ('Hu', 'Hausa'), ('ig', 'Igbo'), ('Yo', 'Yoruba')], max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='language',
        ),
        migrations.AddField(
            model_name='influencer',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
    ]
