# Generated by Django 4.1.3 on 2023-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_language_remove_influencer_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='languages',
            field=models.ManyToManyField(to='users.language'),
        ),
    ]
