# Generated by Django 4.1.3 on 2023-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_influencer_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='language',
        ),
        migrations.AddField(
            model_name='brand',
            name='languages',
            field=models.ManyToManyField(blank=True, max_length=20, to='users.language'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('CNTS', 'Choose Not To Say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='languages',
            field=models.ManyToManyField(blank=True, max_length=20, to='users.language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish'), ('Hindi', 'Hindi'), ('Russian', 'Russian'), ('Japanese', 'Japanese'), ('Arabic', 'Arabic'), ('French', 'French'), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Hausa', 'Hausa'), ('Igbo', 'Igbo'), ('Yoruba', 'Yoruba')], max_length=200, null=True, unique=True),
        ),
    ]
