# Generated by Django 4.1.3 on 2023-01-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='brand',
        ),
    ]
