# Generated by Django 4.1.3 on 2023-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_rate_rating_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='influencer',
        ),
    ]
