# Generated by Django 4.1.3 on 2023-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_rating_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
