# Generated by Django 4.1.3 on 2023-01-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
