# Generated by Django 4.1.3 on 2023-01-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
