<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-01-10 23:00
=======
# Generated by Django 4.1.3 on 2023-01-07 19:46
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_goal_mission_service_vission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vission',
            new_name='Vision',
        ),
    ]
