# Generated by Django 4.1.3 on 2023-01-07 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_followers', models.IntegerField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_followers', models.IntegerField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_followers', models.IntegerField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_followers', models.IntegerField(blank=True, null=True)),
                ('tik_tok_url', models.URLField(blank=True, null=True)),
                ('tit_tok_followers', models.IntegerField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_subscriber', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
